//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_ADBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Painting
    {
        public int id_painting { get; set; }
        public int id_produs { get; set; }
        public int id_type { get; set; }
        public string artist { get; set; }
        public int creation_year { get; set; }
        public decimal length { get; set; }
        public decimal width { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Painting_type Painting_type { get; set; }
    }
}
