//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_ADBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sculpture
    {
        public int id_sculpture { get; set; }
        public int id_product { get; set; }
        public int id_sculpture_material { get; set; }
        public string artist { get; set; }
        public decimal length { get; set; }
        public decimal width { get; set; }
        public decimal depth { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Sculpture_material Sculpture_material { get; set; }
    }
}
