//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_ADBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_role
    {
        public int id_role { get; set; }
        public int id_user { get; set; }
        public int id_tip { get; set; }
        public System.DateTime role_date { get; set; }
    
        public virtual User_type User_type { get; set; }
        public virtual User User { get; set; }
    }
}
