//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_ADBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuctionAppEntities : DbContext
    {
        public AuctionAppEntities()
            : base("name=AuctionAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auction> Auctions { get; set; }
        public virtual DbSet<Auction_type> Auction_types { get; set; }
        public virtual DbSet<Bid> Bids { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Book_condition> Book_conditions { get; set; }
        public virtual DbSet<Jewelry> Jewelries { get; set; }
        public virtual DbSet<Jewelry_type> Jewelry_types { get; set; }
        public virtual DbSet<Painting> Paintings { get; set; }
        public virtual DbSet<Painting_type> Painting_types { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Post_status> Post_status { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Product_image> Product_images { get; set; }
        public virtual DbSet<Sculpture> Sculptures { get; set; }
        public virtual DbSet<Sculpture_material> Sculpture_materials { get; set; }
        public virtual DbSet<User_role> User_roles { get; set; }
        public virtual DbSet<User_type> User_types { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Watch> Watches { get; set; }
        public virtual DbSet<Watch_mechanism> Watch_mechanism { get; set; }
        public virtual DbSet<Watch_type> Watch_types { get; set; }
    }
}
