//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_ADBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int id_book { get; set; }
        public int id_product { get; set; }
        public int id_condition { get; set; }
        public string author { get; set; }
        public int publication_year { get; set; }
        public string publishing_house { get; set; }
        public int page_number { get; set; }
        public string book_language { get; set; }
    
        public virtual Book_condition Book_condition { get; set; }
        public virtual Product Product { get; set; }
    }
}
