//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_ADBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jewelry
    {
        public int id_jewelry { get; set; }
        public int id_product { get; set; }
        public int id_type { get; set; }
        public string brand { get; set; }
        public decimal weight { get; set; }
        public int creation_year { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Jewelry_type Jewelry_type { get; set; }
    }
}
