//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_ADBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Bids = new HashSet<Bid>();
        }
    
        public int id_post { get; set; }
        public int id_product { get; set; }
        public int id_status { get; set; }
        public int id_auction { get; set; }
        public decimal start_price { get; set; }
        public decimal list_price { get; set; }
        public System.DateTime created_at { get; set; }
        public int lot { get; set; }
    
        public virtual Auction Auction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bid> Bids { get; set; }
        public virtual Product Product { get; set; }
        public virtual Post_status Post_status { get; set; }
    }
}
