//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_ADBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Watch
    {
        public int id_watch { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_mechanism { get; set; }
        public decimal diameter { get; set; }
        public string manufacturer { get; set; }
        public int id_type { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Watch_mechanism Watch_mechanism { get; set; }
    }
}
